// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: any_mobile_base_command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Reachy.Sdk.Mobility {

  /// <summary>Holder for reflection information generated from any_mobile_base_command.proto</summary>
  public static partial class AnyMobileBaseCommandReflection {

    #region Descriptor
    /// <summary>File descriptor for any_mobile_base_command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnyMobileBaseCommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1hbnlfbW9iaWxlX2Jhc2VfY29tbWFuZC5wcm90bxITcmVhY2h5LnNkay5t",
            "b2JpbGl0eRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxobZ29v",
            "Z2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhxtb2JpbGVfcGxhdGZvcm1fcmVh",
            "Y2h5LnByb3RvIj0KFFJlc2V0T2RvbWV0cnlNZXNzYWdlEiUKBXJlc2V0GAEg",
            "ASgLMhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IosDChRBbnlNb2JpbGVCYXNl",
            "Q29tbWFuZBI7CghwcmVzZW5jZRgBIAEoCzInLnJlYWNoeS5zZGsubW9iaWxp",
            "dHkuTW9iaWxlQmFzZVByZXNlbmNlSAASRwoQdGFyZ2V0X2RpcmVjdGlvbhgC",
            "IAEoCzIrLnJlYWNoeS5zZGsubW9iaWxpdHkuVGFyZ2V0RGlyZWN0aW9uQ29t",
            "bWFuZEgAEjwKDG1vZGVfY29tbWFuZBgDIAEoCzIkLnJlYWNoeS5zZGsubW9i",
            "aWxpdHkuWnV1dU1vZGVDb21tYW5kSAASMAoFZ29fdG8YBCABKAsyHy5yZWFj",
            "aHkuc2RrLm1vYmlsaXR5LkdvVG9WZWN0b3JIABJDCg5yZXNldF9vZG9tZXRy",
            "eRgFIAEoCzIpLnJlYWNoeS5zZGsubW9iaWxpdHkuUmVzZXRPZG9tZXRyeU1l",
            "c3NhZ2VIABItCgl0aW1lc3RhbXAYDyABKAsyGi5nb29nbGUucHJvdG9idWYu",
            "VGltZXN0YW1wQgkKB2NvbW1hbmRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Reachy.Sdk.Mobility.MobilePlatformReachyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Reachy.Sdk.Mobility.ResetOdometryMessage), global::Reachy.Sdk.Mobility.ResetOdometryMessage.Parser, new[]{ "Reset" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Reachy.Sdk.Mobility.AnyMobileBaseCommand), global::Reachy.Sdk.Mobility.AnyMobileBaseCommand.Parser, new[]{ "Presence", "TargetDirection", "ModeCommand", "GoTo", "ResetOdometry", "Timestamp" }, new[]{ "Command" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ResetOdometryMessage : pb::IMessage<ResetOdometryMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResetOdometryMessage> _parser = new pb::MessageParser<ResetOdometryMessage>(() => new ResetOdometryMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResetOdometryMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reachy.Sdk.Mobility.AnyMobileBaseCommandReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResetOdometryMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResetOdometryMessage(ResetOdometryMessage other) : this() {
      reset_ = other.reset_ != null ? other.reset_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResetOdometryMessage Clone() {
      return new ResetOdometryMessage(this);
    }

    /// <summary>Field number for the "reset" field.</summary>
    public const int ResetFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Empty reset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Empty Reset {
      get { return reset_; }
      set {
        reset_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResetOdometryMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResetOdometryMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Reset, other.Reset)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (reset_ != null) hash ^= Reset.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (reset_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Reset);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (reset_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Reset);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (reset_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reset);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResetOdometryMessage other) {
      if (other == null) {
        return;
      }
      if (other.reset_ != null) {
        if (reset_ == null) {
          Reset = new global::Google.Protobuf.WellKnownTypes.Empty();
        }
        Reset.MergeFrom(other.Reset);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (reset_ == null) {
              Reset = new global::Google.Protobuf.WellKnownTypes.Empty();
            }
            input.ReadMessage(Reset);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (reset_ == null) {
              Reset = new global::Google.Protobuf.WellKnownTypes.Empty();
            }
            input.ReadMessage(Reset);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AnyMobileBaseCommand : pb::IMessage<AnyMobileBaseCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnyMobileBaseCommand> _parser = new pb::MessageParser<AnyMobileBaseCommand>(() => new AnyMobileBaseCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AnyMobileBaseCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reachy.Sdk.Mobility.AnyMobileBaseCommandReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnyMobileBaseCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnyMobileBaseCommand(AnyMobileBaseCommand other) : this() {
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      switch (other.CommandCase) {
        case CommandOneofCase.Presence:
          Presence = other.Presence.Clone();
          break;
        case CommandOneofCase.TargetDirection:
          TargetDirection = other.TargetDirection.Clone();
          break;
        case CommandOneofCase.ModeCommand:
          ModeCommand = other.ModeCommand.Clone();
          break;
        case CommandOneofCase.GoTo:
          GoTo = other.GoTo.Clone();
          break;
        case CommandOneofCase.ResetOdometry:
          ResetOdometry = other.ResetOdometry.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AnyMobileBaseCommand Clone() {
      return new AnyMobileBaseCommand(this);
    }

    /// <summary>Field number for the "presence" field.</summary>
    public const int PresenceFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Mobility.MobileBasePresence Presence {
      get { return commandCase_ == CommandOneofCase.Presence ? (global::Reachy.Sdk.Mobility.MobileBasePresence) command_ : null; }
      set {
        command_ = value;
        commandCase_ = value == null ? CommandOneofCase.None : CommandOneofCase.Presence;
      }
    }

    /// <summary>Field number for the "target_direction" field.</summary>
    public const int TargetDirectionFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Mobility.TargetDirectionCommand TargetDirection {
      get { return commandCase_ == CommandOneofCase.TargetDirection ? (global::Reachy.Sdk.Mobility.TargetDirectionCommand) command_ : null; }
      set {
        command_ = value;
        commandCase_ = value == null ? CommandOneofCase.None : CommandOneofCase.TargetDirection;
      }
    }

    /// <summary>Field number for the "mode_command" field.</summary>
    public const int ModeCommandFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Mobility.ZuuuModeCommand ModeCommand {
      get { return commandCase_ == CommandOneofCase.ModeCommand ? (global::Reachy.Sdk.Mobility.ZuuuModeCommand) command_ : null; }
      set {
        command_ = value;
        commandCase_ = value == null ? CommandOneofCase.None : CommandOneofCase.ModeCommand;
      }
    }

    /// <summary>Field number for the "go_to" field.</summary>
    public const int GoToFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Mobility.GoToVector GoTo {
      get { return commandCase_ == CommandOneofCase.GoTo ? (global::Reachy.Sdk.Mobility.GoToVector) command_ : null; }
      set {
        command_ = value;
        commandCase_ = value == null ? CommandOneofCase.None : CommandOneofCase.GoTo;
      }
    }

    /// <summary>Field number for the "reset_odometry" field.</summary>
    public const int ResetOdometryFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Mobility.ResetOdometryMessage ResetOdometry {
      get { return commandCase_ == CommandOneofCase.ResetOdometry ? (global::Reachy.Sdk.Mobility.ResetOdometryMessage) command_ : null; }
      set {
        command_ = value;
        commandCase_ = value == null ? CommandOneofCase.None : CommandOneofCase.ResetOdometry;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 15;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    private object command_;
    /// <summary>Enum of possible cases for the "command" oneof.</summary>
    public enum CommandOneofCase {
      None = 0,
      Presence = 1,
      TargetDirection = 2,
      ModeCommand = 3,
      GoTo = 4,
      ResetOdometry = 5,
    }
    private CommandOneofCase commandCase_ = CommandOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandOneofCase CommandCase {
      get { return commandCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearCommand() {
      commandCase_ = CommandOneofCase.None;
      command_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AnyMobileBaseCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AnyMobileBaseCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Presence, other.Presence)) return false;
      if (!object.Equals(TargetDirection, other.TargetDirection)) return false;
      if (!object.Equals(ModeCommand, other.ModeCommand)) return false;
      if (!object.Equals(GoTo, other.GoTo)) return false;
      if (!object.Equals(ResetOdometry, other.ResetOdometry)) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (CommandCase != other.CommandCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (commandCase_ == CommandOneofCase.Presence) hash ^= Presence.GetHashCode();
      if (commandCase_ == CommandOneofCase.TargetDirection) hash ^= TargetDirection.GetHashCode();
      if (commandCase_ == CommandOneofCase.ModeCommand) hash ^= ModeCommand.GetHashCode();
      if (commandCase_ == CommandOneofCase.GoTo) hash ^= GoTo.GetHashCode();
      if (commandCase_ == CommandOneofCase.ResetOdometry) hash ^= ResetOdometry.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      hash ^= (int) commandCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (commandCase_ == CommandOneofCase.Presence) {
        output.WriteRawTag(10);
        output.WriteMessage(Presence);
      }
      if (commandCase_ == CommandOneofCase.TargetDirection) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetDirection);
      }
      if (commandCase_ == CommandOneofCase.ModeCommand) {
        output.WriteRawTag(26);
        output.WriteMessage(ModeCommand);
      }
      if (commandCase_ == CommandOneofCase.GoTo) {
        output.WriteRawTag(34);
        output.WriteMessage(GoTo);
      }
      if (commandCase_ == CommandOneofCase.ResetOdometry) {
        output.WriteRawTag(42);
        output.WriteMessage(ResetOdometry);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (commandCase_ == CommandOneofCase.Presence) {
        output.WriteRawTag(10);
        output.WriteMessage(Presence);
      }
      if (commandCase_ == CommandOneofCase.TargetDirection) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetDirection);
      }
      if (commandCase_ == CommandOneofCase.ModeCommand) {
        output.WriteRawTag(26);
        output.WriteMessage(ModeCommand);
      }
      if (commandCase_ == CommandOneofCase.GoTo) {
        output.WriteRawTag(34);
        output.WriteMessage(GoTo);
      }
      if (commandCase_ == CommandOneofCase.ResetOdometry) {
        output.WriteRawTag(42);
        output.WriteMessage(ResetOdometry);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (commandCase_ == CommandOneofCase.Presence) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Presence);
      }
      if (commandCase_ == CommandOneofCase.TargetDirection) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetDirection);
      }
      if (commandCase_ == CommandOneofCase.ModeCommand) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ModeCommand);
      }
      if (commandCase_ == CommandOneofCase.GoTo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoTo);
      }
      if (commandCase_ == CommandOneofCase.ResetOdometry) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResetOdometry);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AnyMobileBaseCommand other) {
      if (other == null) {
        return;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      switch (other.CommandCase) {
        case CommandOneofCase.Presence:
          if (Presence == null) {
            Presence = new global::Reachy.Sdk.Mobility.MobileBasePresence();
          }
          Presence.MergeFrom(other.Presence);
          break;
        case CommandOneofCase.TargetDirection:
          if (TargetDirection == null) {
            TargetDirection = new global::Reachy.Sdk.Mobility.TargetDirectionCommand();
          }
          TargetDirection.MergeFrom(other.TargetDirection);
          break;
        case CommandOneofCase.ModeCommand:
          if (ModeCommand == null) {
            ModeCommand = new global::Reachy.Sdk.Mobility.ZuuuModeCommand();
          }
          ModeCommand.MergeFrom(other.ModeCommand);
          break;
        case CommandOneofCase.GoTo:
          if (GoTo == null) {
            GoTo = new global::Reachy.Sdk.Mobility.GoToVector();
          }
          GoTo.MergeFrom(other.GoTo);
          break;
        case CommandOneofCase.ResetOdometry:
          if (ResetOdometry == null) {
            ResetOdometry = new global::Reachy.Sdk.Mobility.ResetOdometryMessage();
          }
          ResetOdometry.MergeFrom(other.ResetOdometry);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Reachy.Sdk.Mobility.MobileBasePresence subBuilder = new global::Reachy.Sdk.Mobility.MobileBasePresence();
            if (commandCase_ == CommandOneofCase.Presence) {
              subBuilder.MergeFrom(Presence);
            }
            input.ReadMessage(subBuilder);
            Presence = subBuilder;
            break;
          }
          case 18: {
            global::Reachy.Sdk.Mobility.TargetDirectionCommand subBuilder = new global::Reachy.Sdk.Mobility.TargetDirectionCommand();
            if (commandCase_ == CommandOneofCase.TargetDirection) {
              subBuilder.MergeFrom(TargetDirection);
            }
            input.ReadMessage(subBuilder);
            TargetDirection = subBuilder;
            break;
          }
          case 26: {
            global::Reachy.Sdk.Mobility.ZuuuModeCommand subBuilder = new global::Reachy.Sdk.Mobility.ZuuuModeCommand();
            if (commandCase_ == CommandOneofCase.ModeCommand) {
              subBuilder.MergeFrom(ModeCommand);
            }
            input.ReadMessage(subBuilder);
            ModeCommand = subBuilder;
            break;
          }
          case 34: {
            global::Reachy.Sdk.Mobility.GoToVector subBuilder = new global::Reachy.Sdk.Mobility.GoToVector();
            if (commandCase_ == CommandOneofCase.GoTo) {
              subBuilder.MergeFrom(GoTo);
            }
            input.ReadMessage(subBuilder);
            GoTo = subBuilder;
            break;
          }
          case 42: {
            global::Reachy.Sdk.Mobility.ResetOdometryMessage subBuilder = new global::Reachy.Sdk.Mobility.ResetOdometryMessage();
            if (commandCase_ == CommandOneofCase.ResetOdometry) {
              subBuilder.MergeFrom(ResetOdometry);
            }
            input.ReadMessage(subBuilder);
            ResetOdometry = subBuilder;
            break;
          }
          case 122: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Reachy.Sdk.Mobility.MobileBasePresence subBuilder = new global::Reachy.Sdk.Mobility.MobileBasePresence();
            if (commandCase_ == CommandOneofCase.Presence) {
              subBuilder.MergeFrom(Presence);
            }
            input.ReadMessage(subBuilder);
            Presence = subBuilder;
            break;
          }
          case 18: {
            global::Reachy.Sdk.Mobility.TargetDirectionCommand subBuilder = new global::Reachy.Sdk.Mobility.TargetDirectionCommand();
            if (commandCase_ == CommandOneofCase.TargetDirection) {
              subBuilder.MergeFrom(TargetDirection);
            }
            input.ReadMessage(subBuilder);
            TargetDirection = subBuilder;
            break;
          }
          case 26: {
            global::Reachy.Sdk.Mobility.ZuuuModeCommand subBuilder = new global::Reachy.Sdk.Mobility.ZuuuModeCommand();
            if (commandCase_ == CommandOneofCase.ModeCommand) {
              subBuilder.MergeFrom(ModeCommand);
            }
            input.ReadMessage(subBuilder);
            ModeCommand = subBuilder;
            break;
          }
          case 34: {
            global::Reachy.Sdk.Mobility.GoToVector subBuilder = new global::Reachy.Sdk.Mobility.GoToVector();
            if (commandCase_ == CommandOneofCase.GoTo) {
              subBuilder.MergeFrom(GoTo);
            }
            input.ReadMessage(subBuilder);
            GoTo = subBuilder;
            break;
          }
          case 42: {
            global::Reachy.Sdk.Mobility.ResetOdometryMessage subBuilder = new global::Reachy.Sdk.Mobility.ResetOdometryMessage();
            if (commandCase_ == CommandOneofCase.ResetOdometry) {
              subBuilder.MergeFrom(ResetOdometry);
            }
            input.ReadMessage(subBuilder);
            ResetOdometry = subBuilder;
            break;
          }
          case 122: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
