// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Reachy.Sdk.Config {

  /// <summary>Holder for reflection information generated from config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb25maWcucHJvdG8SEXJlYWNoeS5zZGsuY29uZmlnGhtnb29nbGUvcHJv",
            "dG9idWYvZW1wdHkucHJvdG8iWwoMQ29uZmlnUmVhY2h5EhIKCmdlbmVyYXRp",
            "b24YASABKA0SHAoUbW9iaWxlX2Jhc2VfcHJlc2VuY2UYAiABKAgSGQoRY2Ft",
            "ZXJhX3BhcmFtZXRlcnMYAyADKAIyWwoNQ29uZmlnU2VydmljZRJKCg9HZXRS",
            "ZWFjaHlDb25maWcSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaHy5yZWFjaHku",
            "c2RrLmNvbmZpZy5Db25maWdSZWFjaHliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Reachy.Sdk.Config.ConfigReachy), global::Reachy.Sdk.Config.ConfigReachy.Parser, new[]{ "Generation", "MobileBasePresence", "CameraParameters" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConfigReachy : pb::IMessage<ConfigReachy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConfigReachy> _parser = new pb::MessageParser<ConfigReachy>(() => new ConfigReachy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConfigReachy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reachy.Sdk.Config.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigReachy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigReachy(ConfigReachy other) : this() {
      generation_ = other.generation_;
      mobileBasePresence_ = other.mobileBasePresence_;
      cameraParameters_ = other.cameraParameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConfigReachy Clone() {
      return new ConfigReachy(this);
    }

    /// <summary>Field number for the "generation" field.</summary>
    public const int GenerationFieldNumber = 1;
    private uint generation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Generation {
      get { return generation_; }
      set {
        generation_ = value;
      }
    }

    /// <summary>Field number for the "mobile_base_presence" field.</summary>
    public const int MobileBasePresenceFieldNumber = 2;
    private bool mobileBasePresence_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool MobileBasePresence {
      get { return mobileBasePresence_; }
      set {
        mobileBasePresence_ = value;
      }
    }

    /// <summary>Field number for the "camera_parameters" field.</summary>
    public const int CameraParametersFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_cameraParameters_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> cameraParameters_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> CameraParameters {
      get { return cameraParameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConfigReachy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConfigReachy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Generation != other.Generation) return false;
      if (MobileBasePresence != other.MobileBasePresence) return false;
      if(!cameraParameters_.Equals(other.cameraParameters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Generation != 0) hash ^= Generation.GetHashCode();
      if (MobileBasePresence != false) hash ^= MobileBasePresence.GetHashCode();
      hash ^= cameraParameters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Generation != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Generation);
      }
      if (MobileBasePresence != false) {
        output.WriteRawTag(16);
        output.WriteBool(MobileBasePresence);
      }
      cameraParameters_.WriteTo(output, _repeated_cameraParameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Generation != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Generation);
      }
      if (MobileBasePresence != false) {
        output.WriteRawTag(16);
        output.WriteBool(MobileBasePresence);
      }
      cameraParameters_.WriteTo(ref output, _repeated_cameraParameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Generation != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Generation);
      }
      if (MobileBasePresence != false) {
        size += 1 + 1;
      }
      size += cameraParameters_.CalculateSize(_repeated_cameraParameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConfigReachy other) {
      if (other == null) {
        return;
      }
      if (other.Generation != 0) {
        Generation = other.Generation;
      }
      if (other.MobileBasePresence != false) {
        MobileBasePresence = other.MobileBasePresence;
      }
      cameraParameters_.Add(other.cameraParameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Generation = input.ReadUInt32();
            break;
          }
          case 16: {
            MobileBasePresence = input.ReadBool();
            break;
          }
          case 26:
          case 29: {
            cameraParameters_.AddEntriesFrom(input, _repeated_cameraParameters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Generation = input.ReadUInt32();
            break;
          }
          case 16: {
            MobileBasePresence = input.ReadBool();
            break;
          }
          case 26:
          case 29: {
            cameraParameters_.AddEntriesFrom(ref input, _repeated_cameraParameters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
