// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fan.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Sdk.Fan {
  public static partial class FanControllerService
  {
    static readonly string __ServiceName = "reachy.sdk.fan.FanControllerService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Fan.FansId> __Marshaller_reachy_sdk_fan_FansId = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Fan.FansId.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Fan.FansStateRequest> __Marshaller_reachy_sdk_fan_FansStateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Fan.FansStateRequest.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Fan.FansState> __Marshaller_reachy_sdk_fan_FansState = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Fan.FansState.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Fan.FansCommand> __Marshaller_reachy_sdk_fan_FansCommand = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Fan.FansCommand.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Fan.FansCommandAck> __Marshaller_reachy_sdk_fan_FansCommandAck = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Fan.FansCommandAck.Parser));

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Reachy.Sdk.Fan.FansId> __Method_GetAllFansId = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Reachy.Sdk.Fan.FansId>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAllFansId",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_reachy_sdk_fan_FansId);

    static readonly grpc::Method<global::Reachy.Sdk.Fan.FansStateRequest, global::Reachy.Sdk.Fan.FansState> __Method_GetFansState = new grpc::Method<global::Reachy.Sdk.Fan.FansStateRequest, global::Reachy.Sdk.Fan.FansState>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFansState",
        __Marshaller_reachy_sdk_fan_FansStateRequest,
        __Marshaller_reachy_sdk_fan_FansState);

    static readonly grpc::Method<global::Reachy.Sdk.Fan.FansCommand, global::Reachy.Sdk.Fan.FansCommandAck> __Method_SendFansCommands = new grpc::Method<global::Reachy.Sdk.Fan.FansCommand, global::Reachy.Sdk.Fan.FansCommandAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendFansCommands",
        __Marshaller_reachy_sdk_fan_FansCommand,
        __Marshaller_reachy_sdk_fan_FansCommandAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Sdk.Fan.FanReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FanControllerService</summary>
    [grpc::BindServiceMethod(typeof(FanControllerService), "BindService")]
    public abstract partial class FanControllerServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Fan.FansId> GetAllFansId(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Fan.FansState> GetFansState(global::Reachy.Sdk.Fan.FansStateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Fan.FansCommandAck> SendFansCommands(global::Reachy.Sdk.Fan.FansCommand request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FanControllerService</summary>
    public partial class FanControllerServiceClient : grpc::ClientBase<FanControllerServiceClient>
    {
      /// <summary>Creates a new client for FanControllerService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FanControllerServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FanControllerService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FanControllerServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FanControllerServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FanControllerServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Sdk.Fan.FansId GetAllFansId(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllFansId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Fan.FansId GetAllFansId(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAllFansId, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Fan.FansId> GetAllFansIdAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllFansIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Fan.FansId> GetAllFansIdAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAllFansId, null, options, request);
      }
      public virtual global::Reachy.Sdk.Fan.FansState GetFansState(global::Reachy.Sdk.Fan.FansStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFansState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Fan.FansState GetFansState(global::Reachy.Sdk.Fan.FansStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFansState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Fan.FansState> GetFansStateAsync(global::Reachy.Sdk.Fan.FansStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFansStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Fan.FansState> GetFansStateAsync(global::Reachy.Sdk.Fan.FansStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFansState, null, options, request);
      }
      public virtual global::Reachy.Sdk.Fan.FansCommandAck SendFansCommands(global::Reachy.Sdk.Fan.FansCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendFansCommands(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Fan.FansCommandAck SendFansCommands(global::Reachy.Sdk.Fan.FansCommand request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendFansCommands, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Fan.FansCommandAck> SendFansCommandsAsync(global::Reachy.Sdk.Fan.FansCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendFansCommandsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Fan.FansCommandAck> SendFansCommandsAsync(global::Reachy.Sdk.Fan.FansCommand request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendFansCommands, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FanControllerServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FanControllerServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FanControllerServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAllFansId, serviceImpl.GetAllFansId)
          .AddMethod(__Method_GetFansState, serviceImpl.GetFansState)
          .AddMethod(__Method_SendFansCommands, serviceImpl.SendFansCommands).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FanControllerServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAllFansId, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Reachy.Sdk.Fan.FansId>(serviceImpl.GetAllFansId));
      serviceBinder.AddMethod(__Method_GetFansState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Fan.FansStateRequest, global::Reachy.Sdk.Fan.FansState>(serviceImpl.GetFansState));
      serviceBinder.AddMethod(__Method_SendFansCommands, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Fan.FansCommand, global::Reachy.Sdk.Fan.FansCommandAck>(serviceImpl.SendFansCommands));
    }

  }
}
#endregion
