// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: fullbody_cartesian_command.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Sdk.Kinematics {
  public static partial class FullBodyCartesianCommandService
  {
    static readonly string __ServiceName = "reachy.sdk.kinematics.FullBodyCartesianCommandService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand> __Marshaller_reachy_sdk_kinematics_FullBodyCartesianCommand = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> __Marshaller_reachy_sdk_kinematics_FullBodyCartesianCommandAck = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck.Parser));

    static readonly grpc::Method<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> __Method_SendFullBodyCartesianCommands = new grpc::Method<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendFullBodyCartesianCommands",
        __Marshaller_reachy_sdk_kinematics_FullBodyCartesianCommand,
        __Marshaller_reachy_sdk_kinematics_FullBodyCartesianCommandAck);

    static readonly grpc::Method<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> __Method_StreamFullBodyCartesianCommands = new grpc::Method<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "StreamFullBodyCartesianCommands",
        __Marshaller_reachy_sdk_kinematics_FullBodyCartesianCommand,
        __Marshaller_reachy_sdk_kinematics_FullBodyCartesianCommandAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Sdk.Kinematics.FullbodyCartesianCommandReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FullBodyCartesianCommandService</summary>
    [grpc::BindServiceMethod(typeof(FullBodyCartesianCommandService), "BindService")]
    public abstract partial class FullBodyCartesianCommandServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> SendFullBodyCartesianCommands(global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> StreamFullBodyCartesianCommands(grpc::IAsyncStreamReader<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FullBodyCartesianCommandService</summary>
    public partial class FullBodyCartesianCommandServiceClient : grpc::ClientBase<FullBodyCartesianCommandServiceClient>
    {
      /// <summary>Creates a new client for FullBodyCartesianCommandService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FullBodyCartesianCommandServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FullBodyCartesianCommandService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FullBodyCartesianCommandServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FullBodyCartesianCommandServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FullBodyCartesianCommandServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck SendFullBodyCartesianCommands(global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendFullBodyCartesianCommands(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck SendFullBodyCartesianCommands(global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendFullBodyCartesianCommands, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> SendFullBodyCartesianCommandsAsync(global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendFullBodyCartesianCommandsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> SendFullBodyCartesianCommandsAsync(global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendFullBodyCartesianCommands, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> StreamFullBodyCartesianCommands(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamFullBodyCartesianCommands(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck> StreamFullBodyCartesianCommands(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_StreamFullBodyCartesianCommands, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FullBodyCartesianCommandServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FullBodyCartesianCommandServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FullBodyCartesianCommandServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendFullBodyCartesianCommands, serviceImpl.SendFullBodyCartesianCommands)
          .AddMethod(__Method_StreamFullBodyCartesianCommands, serviceImpl.StreamFullBodyCartesianCommands).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FullBodyCartesianCommandServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendFullBodyCartesianCommands, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck>(serviceImpl.SendFullBodyCartesianCommands));
      serviceBinder.AddMethod(__Method_StreamFullBodyCartesianCommands, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Reachy.Sdk.Kinematics.FullBodyCartesianCommand, global::Reachy.Sdk.Kinematics.FullBodyCartesianCommandAck>(serviceImpl.StreamFullBodyCartesianCommands));
    }

  }
}
#endregion
