// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: head_kinematics.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Sdk.Kinematics {
  public static partial class HeadKinematics
  {
    static readonly string __ServiceName = "reachy.sdk.kinematics.HeadKinematics";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.HeadFKRequest> __Marshaller_reachy_sdk_kinematics_HeadFKRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.HeadFKRequest.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.HeadFKSolution> __Marshaller_reachy_sdk_kinematics_HeadFKSolution = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.HeadFKSolution.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.HeadIKRequest> __Marshaller_reachy_sdk_kinematics_HeadIKRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.HeadIKRequest.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.HeadIKSolution> __Marshaller_reachy_sdk_kinematics_HeadIKSolution = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.HeadIKSolution.Parser));

    static readonly grpc::Method<global::Reachy.Sdk.Kinematics.HeadFKRequest, global::Reachy.Sdk.Kinematics.HeadFKSolution> __Method_ComputeHeadFK = new grpc::Method<global::Reachy.Sdk.Kinematics.HeadFKRequest, global::Reachy.Sdk.Kinematics.HeadFKSolution>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ComputeHeadFK",
        __Marshaller_reachy_sdk_kinematics_HeadFKRequest,
        __Marshaller_reachy_sdk_kinematics_HeadFKSolution);

    static readonly grpc::Method<global::Reachy.Sdk.Kinematics.HeadIKRequest, global::Reachy.Sdk.Kinematics.HeadIKSolution> __Method_ComputeHeadIK = new grpc::Method<global::Reachy.Sdk.Kinematics.HeadIKRequest, global::Reachy.Sdk.Kinematics.HeadIKSolution>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ComputeHeadIK",
        __Marshaller_reachy_sdk_kinematics_HeadIKRequest,
        __Marshaller_reachy_sdk_kinematics_HeadIKSolution);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Sdk.Kinematics.HeadKinematicsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HeadKinematics</summary>
    [grpc::BindServiceMethod(typeof(HeadKinematics), "BindService")]
    public abstract partial class HeadKinematicsBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Kinematics.HeadFKSolution> ComputeHeadFK(global::Reachy.Sdk.Kinematics.HeadFKRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Kinematics.HeadIKSolution> ComputeHeadIK(global::Reachy.Sdk.Kinematics.HeadIKRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HeadKinematics</summary>
    public partial class HeadKinematicsClient : grpc::ClientBase<HeadKinematicsClient>
    {
      /// <summary>Creates a new client for HeadKinematics</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HeadKinematicsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HeadKinematics that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HeadKinematicsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HeadKinematicsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HeadKinematicsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Sdk.Kinematics.HeadFKSolution ComputeHeadFK(global::Reachy.Sdk.Kinematics.HeadFKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeHeadFK(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Kinematics.HeadFKSolution ComputeHeadFK(global::Reachy.Sdk.Kinematics.HeadFKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ComputeHeadFK, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.HeadFKSolution> ComputeHeadFKAsync(global::Reachy.Sdk.Kinematics.HeadFKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeHeadFKAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.HeadFKSolution> ComputeHeadFKAsync(global::Reachy.Sdk.Kinematics.HeadFKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ComputeHeadFK, null, options, request);
      }
      public virtual global::Reachy.Sdk.Kinematics.HeadIKSolution ComputeHeadIK(global::Reachy.Sdk.Kinematics.HeadIKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeHeadIK(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Kinematics.HeadIKSolution ComputeHeadIK(global::Reachy.Sdk.Kinematics.HeadIKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ComputeHeadIK, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.HeadIKSolution> ComputeHeadIKAsync(global::Reachy.Sdk.Kinematics.HeadIKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeHeadIKAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.HeadIKSolution> ComputeHeadIKAsync(global::Reachy.Sdk.Kinematics.HeadIKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ComputeHeadIK, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HeadKinematicsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HeadKinematicsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HeadKinematicsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ComputeHeadFK, serviceImpl.ComputeHeadFK)
          .AddMethod(__Method_ComputeHeadIK, serviceImpl.ComputeHeadIK).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HeadKinematicsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ComputeHeadFK, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Kinematics.HeadFKRequest, global::Reachy.Sdk.Kinematics.HeadFKSolution>(serviceImpl.ComputeHeadFK));
      serviceBinder.AddMethod(__Method_ComputeHeadIK, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Kinematics.HeadIKRequest, global::Reachy.Sdk.Kinematics.HeadIKSolution>(serviceImpl.ComputeHeadIK));
    }

  }
}
#endregion
