// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: realsense.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Reachy.Sdk.Realsense {

  /// <summary>Holder for reflection information generated from realsense.proto</summary>
  public static partial class RealsenseReflection {

    #region Descriptor
    /// <summary>File descriptor for realsense.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RealsenseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9yZWFsc2Vuc2UucHJvdG8SFHJlYWNoeS5zZGsucmVhbHNlbnNlGh5nb29n",
            "bGUvcHJvdG9idWYvd3JhcHBlcnMucHJvdG8ifwoFUG9pbnQSJgoBeBgBIAEo",
            "CzIbLmdvb2dsZS5wcm90b2J1Zi5GbG9hdFZhbHVlEiYKAXkYAiABKAsyGy5n",
            "b29nbGUucHJvdG9idWYuRmxvYXRWYWx1ZRImCgF6GAMgASgLMhsuZ29vZ2xl",
            "LnByb3RvYnVmLkZsb2F0VmFsdWUiPgoKUG9pbnRDbG91ZBIwCgtwb2ludF9j",
            "bG91ZBgEIAMoCzIbLnJlYWNoeS5zZGsucmVhbHNlbnNlLlBvaW50IngKEVBv",
            "aW50Q2xvdWRNZXNzYWdlEjAKBmdyb3VuZBgFIAEoCzIgLnJlYWNoeS5zZGsu",
            "cmVhbHNlbnNlLlBvaW50Q2xvdWQSMQoHb2JqZWN0cxgGIAEoCzIgLnJlYWNo",
            "eS5zZGsucmVhbHNlbnNlLlBvaW50Q2xvdWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Reachy.Sdk.Realsense.Point), global::Reachy.Sdk.Realsense.Point.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Reachy.Sdk.Realsense.PointCloud), global::Reachy.Sdk.Realsense.PointCloud.Parser, new[]{ "PointCloud_" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Reachy.Sdk.Realsense.PointCloudMessage), global::Reachy.Sdk.Realsense.PointCloudMessage.Parser, new[]{ "Ground", "Objects" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Point : pb::IMessage<Point>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Point> _parser = new pb::MessageParser<Point>(() => new Point());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Point> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reachy.Sdk.Realsense.RealsenseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point(Point other) : this() {
      X = other.X;
      Y = other.Y;
      Z = other.Z;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Point Clone() {
      return new Point(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private static readonly pb::FieldCodec<float?> _single_x_codec = pb::FieldCodec.ForStructWrapper<float>(10);
    private float? x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? X {
      get { return x_; }
      set {
        x_ = value;
      }
    }


    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private static readonly pb::FieldCodec<float?> _single_y_codec = pb::FieldCodec.ForStructWrapper<float>(18);
    private float? y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }


    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private static readonly pb::FieldCodec<float?> _single_z_codec = pb::FieldCodec.ForStructWrapper<float>(26);
    private float? z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float? Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Point);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Point other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (x_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(X);
      if (y_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(Y);
      if (z_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (x_ != null) {
        _single_x_codec.WriteTagAndValue(output, X);
      }
      if (y_ != null) {
        _single_y_codec.WriteTagAndValue(output, Y);
      }
      if (z_ != null) {
        _single_z_codec.WriteTagAndValue(output, Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (x_ != null) {
        _single_x_codec.WriteTagAndValue(ref output, X);
      }
      if (y_ != null) {
        _single_y_codec.WriteTagAndValue(ref output, Y);
      }
      if (z_ != null) {
        _single_z_codec.WriteTagAndValue(ref output, Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (x_ != null) {
        size += _single_x_codec.CalculateSizeWithTag(X);
      }
      if (y_ != null) {
        size += _single_y_codec.CalculateSizeWithTag(Y);
      }
      if (z_ != null) {
        size += _single_z_codec.CalculateSizeWithTag(Z);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Point other) {
      if (other == null) {
        return;
      }
      if (other.x_ != null) {
        if (x_ == null || other.X != 0F) {
          X = other.X;
        }
      }
      if (other.y_ != null) {
        if (y_ == null || other.Y != 0F) {
          Y = other.Y;
        }
      }
      if (other.z_ != null) {
        if (z_ == null || other.Z != 0F) {
          Z = other.Z;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            float? value = _single_x_codec.Read(input);
            if (x_ == null || value != 0F) {
              X = value;
            }
            break;
          }
          case 18: {
            float? value = _single_y_codec.Read(input);
            if (y_ == null || value != 0F) {
              Y = value;
            }
            break;
          }
          case 26: {
            float? value = _single_z_codec.Read(input);
            if (z_ == null || value != 0F) {
              Z = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            float? value = _single_x_codec.Read(ref input);
            if (x_ == null || value != 0F) {
              X = value;
            }
            break;
          }
          case 18: {
            float? value = _single_y_codec.Read(ref input);
            if (y_ == null || value != 0F) {
              Y = value;
            }
            break;
          }
          case 26: {
            float? value = _single_z_codec.Read(ref input);
            if (z_ == null || value != 0F) {
              Z = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PointCloud : pb::IMessage<PointCloud>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PointCloud> _parser = new pb::MessageParser<PointCloud>(() => new PointCloud());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PointCloud> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reachy.Sdk.Realsense.RealsenseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PointCloud() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PointCloud(PointCloud other) : this() {
      pointCloud_ = other.pointCloud_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PointCloud Clone() {
      return new PointCloud(this);
    }

    /// <summary>Field number for the "point_cloud" field.</summary>
    public const int PointCloud_FieldNumber = 4;
    private static readonly pb::FieldCodec<global::Reachy.Sdk.Realsense.Point> _repeated_pointCloud_codec
        = pb::FieldCodec.ForMessage(34, global::Reachy.Sdk.Realsense.Point.Parser);
    private readonly pbc::RepeatedField<global::Reachy.Sdk.Realsense.Point> pointCloud_ = new pbc::RepeatedField<global::Reachy.Sdk.Realsense.Point>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Reachy.Sdk.Realsense.Point> PointCloud_ {
      get { return pointCloud_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PointCloud);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PointCloud other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pointCloud_.Equals(other.pointCloud_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pointCloud_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      pointCloud_.WriteTo(output, _repeated_pointCloud_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      pointCloud_.WriteTo(ref output, _repeated_pointCloud_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += pointCloud_.CalculateSize(_repeated_pointCloud_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PointCloud other) {
      if (other == null) {
        return;
      }
      pointCloud_.Add(other.pointCloud_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 34: {
            pointCloud_.AddEntriesFrom(input, _repeated_pointCloud_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 34: {
            pointCloud_.AddEntriesFrom(ref input, _repeated_pointCloud_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PointCloudMessage : pb::IMessage<PointCloudMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PointCloudMessage> _parser = new pb::MessageParser<PointCloudMessage>(() => new PointCloudMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PointCloudMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reachy.Sdk.Realsense.RealsenseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PointCloudMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PointCloudMessage(PointCloudMessage other) : this() {
      ground_ = other.ground_ != null ? other.ground_.Clone() : null;
      objects_ = other.objects_ != null ? other.objects_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PointCloudMessage Clone() {
      return new PointCloudMessage(this);
    }

    /// <summary>Field number for the "ground" field.</summary>
    public const int GroundFieldNumber = 5;
    private global::Reachy.Sdk.Realsense.PointCloud ground_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Realsense.PointCloud Ground {
      get { return ground_; }
      set {
        ground_ = value;
      }
    }

    /// <summary>Field number for the "objects" field.</summary>
    public const int ObjectsFieldNumber = 6;
    private global::Reachy.Sdk.Realsense.PointCloud objects_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reachy.Sdk.Realsense.PointCloud Objects {
      get { return objects_; }
      set {
        objects_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PointCloudMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PointCloudMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Ground, other.Ground)) return false;
      if (!object.Equals(Objects, other.Objects)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ground_ != null) hash ^= Ground.GetHashCode();
      if (objects_ != null) hash ^= Objects.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ground_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Ground);
      }
      if (objects_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Objects);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ground_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Ground);
      }
      if (objects_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Objects);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ground_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ground);
      }
      if (objects_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Objects);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PointCloudMessage other) {
      if (other == null) {
        return;
      }
      if (other.ground_ != null) {
        if (ground_ == null) {
          Ground = new global::Reachy.Sdk.Realsense.PointCloud();
        }
        Ground.MergeFrom(other.Ground);
      }
      if (other.objects_ != null) {
        if (objects_ == null) {
          Objects = new global::Reachy.Sdk.Realsense.PointCloud();
        }
        Objects.MergeFrom(other.Objects);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 42: {
            if (ground_ == null) {
              Ground = new global::Reachy.Sdk.Realsense.PointCloud();
            }
            input.ReadMessage(Ground);
            break;
          }
          case 50: {
            if (objects_ == null) {
              Objects = new global::Reachy.Sdk.Realsense.PointCloud();
            }
            input.ReadMessage(Objects);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 42: {
            if (ground_ == null) {
              Ground = new global::Reachy.Sdk.Realsense.PointCloud();
            }
            input.ReadMessage(Ground);
            break;
          }
          case 50: {
            if (objects_ == null) {
              Objects = new global::Reachy.Sdk.Realsense.PointCloud();
            }
            input.ReadMessage(Objects);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
