// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: restart_signal.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Sdk.Restart {
  public static partial class RestartService
  {
    static readonly string __ServiceName = "reachy.sdk.restart.RestartService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Reachy.Sdk.Restart.RestartCmd> __Marshaller_reachy_sdk_restart_RestartCmd = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Restart.RestartCmd.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Restart.RestartSignalAck> __Marshaller_reachy_sdk_restart_RestartSignalAck = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Restart.RestartSignalAck.Parser));

    static readonly grpc::Method<global::Reachy.Sdk.Restart.RestartCmd, global::Reachy.Sdk.Restart.RestartSignalAck> __Method_SendRestartSignal = new grpc::Method<global::Reachy.Sdk.Restart.RestartCmd, global::Reachy.Sdk.Restart.RestartSignalAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendRestartSignal",
        __Marshaller_reachy_sdk_restart_RestartCmd,
        __Marshaller_reachy_sdk_restart_RestartSignalAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Sdk.Restart.RestartSignalReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RestartService</summary>
    [grpc::BindServiceMethod(typeof(RestartService), "BindService")]
    public abstract partial class RestartServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Restart.RestartSignalAck> SendRestartSignal(global::Reachy.Sdk.Restart.RestartCmd request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RestartService</summary>
    public partial class RestartServiceClient : grpc::ClientBase<RestartServiceClient>
    {
      /// <summary>Creates a new client for RestartService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RestartServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RestartService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RestartServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RestartServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RestartServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Sdk.Restart.RestartSignalAck SendRestartSignal(global::Reachy.Sdk.Restart.RestartCmd request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendRestartSignal(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Restart.RestartSignalAck SendRestartSignal(global::Reachy.Sdk.Restart.RestartCmd request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendRestartSignal, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Restart.RestartSignalAck> SendRestartSignalAsync(global::Reachy.Sdk.Restart.RestartCmd request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendRestartSignalAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Restart.RestartSignalAck> SendRestartSignalAsync(global::Reachy.Sdk.Restart.RestartCmd request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendRestartSignal, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RestartServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RestartServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RestartServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendRestartSignal, serviceImpl.SendRestartSignal).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RestartServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendRestartSignal, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Restart.RestartCmd, global::Reachy.Sdk.Restart.RestartSignalAck>(serviceImpl.SendRestartSignal));
    }

  }
}
#endregion
